services:
    simulation:
        build: ./docker/simulation
        container_name: simulation
        network_mode: "host"
        environment:
            - ROS_DOMAIN_ID=1
        stdin_open: true
        # command: ["bash", "-c", "source /ros_ws/install/setup.bash && ros2 launch warehouse_simulation_pkg simulation.launch.py"]
        volumes:
            - maps:/data/maps
            - ./src/warehouse_nav_pkg:/ros_ws/src/warehouse_simulation_pkg
    
    task_manager:
        build: ./docker/task_manager
        container_name: task_manager
        network_mode: "host"
        environment:
            - ROS_DOMAIN_ID=1
        stdin_open: true
        # command: ["bash", "-c", "source /ros_ws/install/setup.bash && ros2 launch warehouse_simulation_pkg task_manager.launch.py"]
        volumes:
            - maps:/data/maps
            - ./src/warehouse_nav_pkg:/ros_ws/src/warehouse_mission_control_pkg
        
    delivery_bot:
        build: ./docker/delivery_bot
        container_name: delivery_bot
        network_mode: "host"
        environment:
            - ROS_DOMAIN_ID=1
        stdin_open: true
        # command: ["bash", "-c", "source /ros_ws/install/setup.bash && ros2 launch warehouse_simulation_pkg delivery_bot.launch.py"]
        volumes:
            - maps:/data/maps
            - ./src/warehouse_bot_pkg:/ros_ws/src/warehouse_bot_pkg
            - ./src/warehouse_nav_pkg:/ros_ws/src/warehouse_nav_pkg
    
    picker_bot:
        build: ./docker/picker_bot
        container_name: picker_bot
        network_mode: "host"
        environment:
            - ROS_DOMAIN_ID=1
        stdin_open: true
        # command: ["bash", "-c", "source /ros_ws/install/setup.bash && ros2 launch warehouse_simulation_pkg picker_bot.launch.py"]
        volumes:
            - maps:/data/maps
            - ./src/warehouse_bot_pkg:/ros_ws/src/warehouse_bot_pkg
            - ./src/warehouse_nav_pkg:/ros_ws/src/warehouse_nav_pkg
    

volumes:
  maps: